# Generated by Django 4.2 on 2023-04-17 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertype',
            name='answer_dt',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 58, 7, 543553)),
            preserve_default=False,
        ),
    ]
