# Generated by Django 4.2 on 2023-04-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_answer_remove_answertext_answertype_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoDcAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('value', models.BooleanField(null=True)),
            ],
            bases=('survey.answer',),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='answer_type',
            field=models.CharField(choices=[('rating', 'rating 1 - 5'), ('text', 'Text'), ('yes_no', 'yes - no'), ('yes_no_dc', "yes, no, don't care")], default='text', max_length=200),
        ),
    ]
