# Generated by Django 4.2 on 2023-04-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_yesnodcanswer_alter_surveyquestion_answer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textanswer',
            old_name='text',
            new_name='value',
        ),
    ]
