# Generated by Django 4.2 on 2023-05-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_rename_text_textanswer_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.answer')),
                ('value', models.IntegerField()),
            ],
            bases=('survey.answer',),
        ),
    ]
