# Generated by Django 5.0.1 on 2024-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_surveyquestion_answer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVSP1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participation', models.BooleanField()),
                ('journey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RVSP2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participation_1st', models.BooleanField()),
                ('participation_2nd', models.BooleanField()),
                ('journey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RVSP3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('will_have_second', models.BooleanField()),
                ('name_2nd', models.CharField(max_length=255)),
                ('participation_1st', models.BooleanField()),
                ('participation_2nd', models.BooleanField()),
                ('journey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RVSP4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participation_1st', models.BooleanField()),
                ('participation_2nd', models.BooleanField()),
                ('participation_children', models.BooleanField()),
                ('children_place', models.IntegerField()),
                ('journey', models.IntegerField()),
            ],
        ),
    ]
