# Generated by Django 5.0.1 on 2024-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_rvsp1_rvsp2_rvsp3_rvsp4'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsp4',
            name='children_food',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
