# Generated by Django 5.0.1 on 2024-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_rvsp4_children_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvsp3',
            name='will_have_second',
        ),
    ]
