# Generated by Django 4.2 on 2023-04-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoblock',
            old_name='block_name',
            new_name='name',
        ),
    ]
