# Generated by Django 4.2 on 2023-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_information_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
