# Generated by Django 4.2 on 2023-05-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_information_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='block',
        ),
        migrations.DeleteModel(
            name='InfoBlock',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
